from datetime import datetime
from database.connection import get_db

class ClipRepository:
    def __init__(self):
        self.db = get_db()
        self.collection = self.db["clips"]

    def create_clip(self, clip_id: str, video_id: str, filename: str,
                    start: float, duration: int, mood: str, index: int, score: float = 0.0) -> dict:
        """
        Creates a metadata logging document for an extracted video clip.
        """
        doc = {
            "clip_id": clip_id,
            "video_id": video_id,
            "filename": filename,
            "start": start,
            "duration": duration,
            "mood": mood,
            "index": index,
            "score": score,
            "ai_content": {
                "title": None,
                "description": None,
                "hashtags": [],
                "keywords": []
            },
            "created_at": datetime.utcnow().isoformat()
        }
        self.collection.insert_one(doc)
        return doc

    def get_clip(self, clip_id: str) -> dict:
        """
        Retrieves a clip by its unique ID.
        """
        return self.collection.find_one({"clip_id": clip_id})

    def get_clips_for_video(self, video_id: str):
        """
        Retrieves all clips associated with a source video, sorted by index.
        """
        return list(self.collection.find({"video_id": video_id}).sort("index", 1))

    def update_ai_content(self, clip_id: str, title: str, description: str, hashtags: list, keywords: list) -> bool:
        """
        Updates metadata generated by the AI Copywriter.
        """
        result = self.collection.update_one(
            {"clip_id": clip_id},
            {
                "$set": {
                    "ai_content": {
                        "title": title,
                        "description": description,
                        "hashtags": hashtags or [],
                        "keywords": keywords or []
                    }
                }
            }
        )
        return result.modified_count > 0

    def delete_clip(self, clip_id: str) -> bool:
        """
        Removes a clip metadata log from the collection.
        """
        result = self.collection.delete_one({"clip_id": clip_id})
        return result.deleted_count > 0

    def get_user_clips(self, email: str):
        """
        Performs an aggregation query to locate all clips generated for a user's uploaded videos.
        """
        pipeline = [
            # 1. Join with videos collection
            {
                "$lookup": {
                    "from": "videos",
                    "localField": "video_id",
                    "foreignField": "video_id",
                    "as": "video_info"
                }
            },
            # 2. Flatten output array
            {"$unwind": "$video_info"},
            # 3. Filter by owner email
            {"$match": {"video_info.uploaded_by": email.strip().lower()}},
            # 4. Sort by creation date
            {"$sort": {"created_at": -1}}
        ]
        return list(self.collection.aggregate(pipeline))
